extended_spam_headers = true;
use = ["x-spamd-bar", "x-spam-level", "x-spam-status", "authentication-results"];
authenticated_headers = ["authentication-results"];
skip_local = false;
skip_authenticated = true;
